from django.conf.urls import patterns, url
from pessoa import views

urlpatterns = patterns('',
    url(r'^$', 'pessoa.views.api_root'),
    url(r'^pessoa/$',
        views.PessoaList.as_view(),
        name='pessoa-list',
    ),
    url(r'^pessoa/(?P<pk>\d+)/$',
        views.PessoaDetail.as_view(),
        name='pessoa-detail',
    ),
    url(r'^pessoatelefone/$',
        views.PessoaTelefoneList.as_view(),
        name='pessoatelefone-list',
    ),
    url(r'^pessoatelefone/(?P<pk>\d+)/$',
        views.PessoaTelefoneDetail.as_view(),
        name='pessoatelefone-detail',
    ),
    url(r'^pessoaendereco/$',
        views.PessoaEnderecoList.as_view(),
        name='pessoaendereco-list',
    ),
    url(r'^pessoaendereco/(?P<pk>\d+)/$',
        views.PessoaEnderecoDetail.as_view(),
        name='pessoaendereco-detail',
    ),
)