# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipoPessoa',
            field=models.CharField(choices=[('F', 'Fisica'), ('J', 'Juridica')], default='F', max_length=1, verbose_name='Tipo Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='estado',
            field=models.CharField(choices=[('CE', 'Ceara'), ('SP', 'Sao Paulo'), ('--', 'Escolha uma UF')], default='--', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='logradouro',
            field=models.CharField(choices=[('rua', 'Rua'), ('ave', 'Avenida')], default='rua', max_length=3, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='tipoEndereco',
            field=models.CharField(choices=[('res', 'Residencial'), ('cob', 'Cobranca')], default='res', max_length=3, verbose_name='Tipo Endereço'),
        ),
        migrations.AlterField(
            model_name='pessoatelefone',
            name='tipoTelefone',
            field=models.CharField(choices=[('Fix', 'Fixo'), ('Cel', 'Celular')], default='fix', max_length=3, verbose_name='Tipo Telefone'),
        ),
    ]
